version: '3.7'

services:
   mysqldb:
     image: ozgurozturknet/webdb
     environment:
      MYSQL_DATABASE: proje
      MYSQL_USER: projemaster
      MYSQL_PASSWORD: master1234
      MYSQL_ROOT_PASSWORD: master1234
     networks:
      - webnet

   websrv:
     image: ozgurozturknet/webkayit # build . ==> imagenin onceden olusturulmasi gerekiyor.
     deploy:
        replicas: 3
        update_config: # ilerde update edecek olursak update kurallarini belirliyoruz
          parallelism: 2 
          delay: 10s
          order: stop-first # once durdur sonra yeni olustur
     depends_on:
       - mysqldb
     ports:
       - "80:80"
     restart: always
     networks:
       - webnet
     environment:
       DB_SERVER: mysqldb
       DB_USERNAME: projemaster
       DB_PASS: master1234
       DB_NAME: proje
networks:
  webnet:
    driver: overlay # bridge docker compose da olusturmustuk